/**
 * ============================================
 * ASSIGNED TO: Member 1 (Frontend Lead)
 * 
 * Budget Results Display Component
 * 
 * TODO:
 * 1. Add a pie chart or bar chart visualization
 *    (Consider using recharts or chart.js)
 * 2. Improve the formatting of AI-generated text
 * 3. Add "copy" or "share" functionality
 * 4. Make the insights more visually distinct
 * ============================================
 */

function BudgetResults({ results }) {
  if (!results) return null

  const { analysis, breakdown, insights } = results

  return (
    <div className="bg-white rounded-xl shadow-lg p-6 md:p-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">
        Your Budget Analysis
      </h2>

      {/* AI-Generated Analysis */}
      {analysis && (
        <div className="mb-8">
          <h3 className="text-lg font-semibold text-gray-700 mb-3">
            Analysis
          </h3>
          <div className="bg-green-50 border-l-4 border-green-500 p-4 rounded-r-lg">
            <p className="text-gray-700 whitespace-pre-line">
              {analysis}
            </p>
          </div>
        </div>
      )}

      {/* Expense Breakdown */}
      {breakdown && breakdown.length > 0 && (
        <div className="mb-8">
          <h3 className="text-lg font-semibold text-gray-700 mb-3">
            Expense Breakdown
          </h3>
          <div className="space-y-3">
            {breakdown.map((item, index) => (
              <div key={index} className="flex items-center">
                <div className="flex-1">
                  <div className="flex justify-between text-sm mb-1">
                    <span className="font-medium text-gray-700">
                      {item.category}
                    </span>
                    <span className="text-gray-600">
                      ${item.amount.toFixed(2)} ({item.percentage.toFixed(1)}%)
                    </span>
                  </div>
                  {/* Progress Bar */}
                  <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-green-500 rounded-full transition-all duration-500"
                      style={{ width: `${Math.min(item.percentage, 100)}%` }}
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Key Insights */}
      {insights && insights.length > 0 && (
        <div className="mb-6">
          <h3 className="text-lg font-semibold text-gray-700 mb-3">
            Key Insights
          </h3>
          <ul className="space-y-2">
            {insights.map((insight, index) => (
              <li 
                key={index}
                className="flex items-start space-x-2 text-gray-700"
              >
                <span className="text-green-500 mt-1">-</span>
                <span>{insight}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* 
        TODO (Member 1): Add a visualization component here
        Consider using a library like:
        - recharts: npm install recharts
        - chart.js: npm install chart.js react-chartjs-2
        
        Example pie chart showing expense distribution would be helpful
      */}
      <div className="mt-6 p-4 bg-gray-100 rounded-lg text-center text-gray-500">
        <p>Chart visualization coming soon!</p>
        <p className="text-sm">TODO: Add pie chart or bar chart here</p>
      </div>

      {/* Disclaimer */}
      <p className="mt-6 text-xs text-gray-500 italic">
        This analysis is generated by AI for educational purposes only 
        and does not constitute financial advice.
      </p>
    </div>
  )
}

export default BudgetResults
